version: '3.3'

services:
  caiman:
    build:
      context: .
    volumes:
       - ./CaImAn:/caiman
    environment:
      MKL_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
      VECLIB_MAXIMUM_THREADS: 1
